# .github/workflows/docker-build.yml

# Название рабочего процесса, которое будет отображаться в интерфейсе GitHub Actions.
name: Docker Image CI

# Определяет, когда этот рабочий процесс будет запускаться.
on:
  # Запускать при каждом push в ветку 'main'.
  push:
    branches: [ main ]
  # Запускать вручную из интерфейса GitHub Actions.
  workflow_dispatch:

# Задачи (jobs), которые будут выполняться в рамках этого рабочего процесса.
jobs:
  # Название задачи.
  build:
    # Тип раннера (виртуальной машины), на которой будет выполняться задача.
    runs-on: ubuntu-latest

    # Шаги (steps) для выполнения задачи.
    steps:
    # Шаг 1: Проверка кода.
    # Использует action 'actions/checkout@v4' для клонирования вашего репозитория
    # на раннер GitHub Actions. Это необходимо, чтобы получить доступ к Dockerfile и коду.
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Настройка Node.js.
    # Этот шаг устанавливает Node.js на раннер, что необходимо для выполнения 'npm install' и 'npm test'.
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Укажите версию Node.js, которую вы используете или предпочитаете

    # Шаг 3: Установка зависимостей Node.js.
    # Запускает 'npm install' для установки всех зависимостей, включая devDependencies,
    # которые нужны для тестирования.
    - name: Install Node.js dependencies
      run: npm install

    # Шаг 4: Запуск тестов.
    # Выполняет команду 'npm test', которая, как мы настроили, запускает Mocha.
    - name: Run tests
      run: npm test

    # Шаг 5: Настройка Docker Buildx (рекомендуется для современных сборок).
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Шаг 6: Сборка Docker-образа.
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: my-devops-node-app:latest
